import type {
  VoiceAgent,
  VoicePhoneNumber,
  VoiceCall,
  VoiceCampaign,
  VoiceTelephonySettings,
} from '@/types/voice-calling';

export const VOICE_PERSONAS = [
  {
    id: 'priya-indian-natural',
    name: 'Priya (Natural Indian Female - Warm & Courteous)',
    provider: 'elevenlabs' as const,
    gender: 'Female',
    accent: 'Indian (Neutral English / Hindi / Urdu)',
    description: 'Ultra-natural human female voice with polite Indian cadence. Zero robotic tone.',
    sampleAudioText: 'Namaste! Thank you for calling Apex Business Services. Main Priya bol rahi hoon, aapki kya madad kar sakti hoon?',
  },
  {
    id: 'neerja-indian-natural',
    name: 'Neerja (Professional Indian Executive)',
    provider: 'elevenlabs' as const,
    gender: 'Female',
    accent: 'Indian English',
    description: 'Crisp, articulate corporate Indian receptionist tone, ideal for B2B sales & hot leads.',
    sampleAudioText: 'Hello! This is Neerja calling from Jeose CRM. How may I assist your business growth today?',
  },
  {
    id: 'swara-indian-hindi',
    name: 'Swara (Fluent Hindi & Urdu Speaker)',
    provider: 'elevenlabs' as const,
    gender: 'Female',
    accent: 'Hindi / Urdu / English',
    description: 'Gentle, soothing Indian tone for clinics, salons, and customer reception.',
    sampleAudioText: 'Namaste aur Assalam-o-Alaikum! Hamare clinic me aapka swagat hai. Main aapki booking confirm kar sakti hoon.',
  },
  {
    id: '21m00Tcm4TlvDq8ikWAM',
    name: 'Rachel (Warm & Empathetic)',
    provider: 'elevenlabs' as const,
    gender: 'Female',
    accent: 'American (Neutral)',
    description: 'Natural international voice for overseas global clients',
    sampleAudioText: 'Thank you for calling! I would be delighted to help you schedule an appointment.',
  },
  {
    id: 'EXAVITQu4vr4xnSDxMaL',
    name: 'Serena (Executive & Polished)',
    provider: 'elevenlabs' as const,
    gender: 'Female',
    accent: 'British',
    description: 'Sophisticated tone for luxury sales and VIP concierge',
    sampleAudioText: 'Good afternoon. Welcome to Prime Properties. May I assist you with your investment search?',
  },
];

export const INITIAL_VOICE_AGENTS: VoiceAgent[] = [
  {
    id: 'agent-receptionist-1',
    name: 'Priya - 24/7 Frontdesk AI Receptionist (Indian Female Voice)',
    type: 'receptionist',
    status: 'active',
    voiceProvider: 'elevenlabs',
    voiceId: 'priya-indian-natural',
    voiceName: 'Priya (Natural Indian Female)',
    language: 'en-IN',
    llmModel: 'gpt-4o-mini',
    firstMessage: 'Namaste! Thank you for calling Apex Business Services. My name is Priya, your receptionist. Aapki kis tarah madad kar sakti hoon? How may I assist you today?',
    systemPrompt: `You are Priya, a courteous, warm, and highly professional Indian female AI Frontdesk Receptionist for Apex Business Services.
Your persona & mannerisms:
1. Speak in a polite, respectful, and natural tone (Hinglish/Urdu/English blend when appropriate, like a cultured receptionist in Delhi/Mumbai/Dubai).
2. Warmly greet callers, identify their inquiry, and answer questions about company services, appointment timings, and pricing.
3. If the caller asks to book an appointment, offer slots: tomorrow morning at 11:00 AM or afternoon at 3:30 PM. Collect their full name and phone number.
4. If they need urgent escalation, smoothly transfer the call to the emergency support team at +1 (555) 019-2831.
5. Keep your tone completely natural, friendly, and never sound like a robotic machine.`,
    temperature: 0.65,
    silenceTimeoutSeconds: 12,
    interruptionHandling: true,
    transferPhoneNumber: '+1 (555) 019-2831',
    createdAt: '2026-09-15T08:00:00Z',
    updatedAt: '2026-10-01T12:00:00Z',
  },
  {
    id: 'agent-marketing-2',
    name: 'Ananya - Outbound Marketing & Leads Qualifier (Indian Female Voice)',
    type: 'outbound_marketing',
    status: 'active',
    voiceProvider: 'elevenlabs',
    voiceId: 'neerja-indian-natural',
    voiceName: 'Neerja (Professional Indian Executive)',
    language: 'en-IN',
    llmModel: 'gpt-4o',
    firstMessage: 'Hello! Main Ananya baat kar rahi hoon Jeose CRM se. I saw your business inquiry and wanted to quickly share how our AI calling doubles your customer bookings.',
    systemPrompt: `You are Ananya, an expert and energetic Indian female AI Sales Development Representative (SDR) calling business leads.
Your goals:
1. Greet courteously and hook the lead within the first 10 seconds: "Hum businesses ko 24/7 AI Receptionist provide karte hain jo missed calls ko 40% bookings me convert karti hai."
2. Handle objections with pleasant politeness:
   - "Busy right now": "Main bilkul samajh sakti hoon! Kal 3 baje 2 minute baat karne ka theek waqt rahega?"
   - "Price kitna hai?": "Plans sirf $49/month se shuru hote hain with unlimited calls."
3. When interested, qualify as a Hot Lead and schedule a personalized 15-minute walkthrough.`,
    temperature: 0.70,
    silenceTimeoutSeconds: 10,
    interruptionHandling: true,
    transferPhoneNumber: '+1 (555) 948-2300',
    createdAt: '2026-09-20T10:30:00Z',
    updatedAt: '2026-10-05T14:15:00Z',
  },
  {
    id: 'agent-healthcare-3',
    name: 'Dr. Sarah - Clinic & Dental Appointment Setter',
    type: 'receptionist',
    status: 'active',
    voiceProvider: 'openai',
    voiceId: 'nova',
    voiceName: 'Nova (Energetic & Friendly)',
    language: 'en-US',
    llmModel: 'gpt-4o-mini',
    firstMessage: 'Hello! Thank you for calling Prime Smiles Dental & Wellness Clinic. This is Sarah, how can I help you book or reschedule your visit?',
    systemPrompt: `You are Sarah, the dedicated AI Patient Coordinator for Prime Smiles Dental Clinic.
1. Inquire if the patient is visiting for a routine cleaning, dental implant, teeth whitening, or emergency pain relief.
2. Collect the patient name, contact number, and insurance provider.
3. Offer morning (10:00 AM) or afternoon (3:30 PM) slots.
4. For severe toothaches or emergencies, provide first-aid guidance and immediately route to the on-call doctor.`,
    temperature: 0.60,
    silenceTimeoutSeconds: 15,
    interruptionHandling: true,
    transferPhoneNumber: '+1 (555) 442-9901',
    createdAt: '2026-09-25T11:00:00Z',
    updatedAt: '2026-10-06T16:20:00Z',
  },
];

export const INITIAL_PHONE_NUMBERS: VoicePhoneNumber[] = [
  {
    id: 'num-1',
    phoneNumber: '+1 (415) 890-3421',
    friendlyName: 'US Main Office Virtual Receptionist',
    provider: 'twilio',
    assignedAgentId: 'agent-receptionist-1',
    assignedAgentName: 'Maya - 24/7 Frontdesk AI Receptionist',
    status: 'active',
    capabilities: { voice: true, sms: true },
    createdAt: '2026-09-10T14:00:00Z',
    updatedAt: '2026-09-10T14:00:00Z',
  },
  {
    id: 'num-2',
    phoneNumber: '+1 (650) 438-7712',
    friendlyName: 'Outbound Marketing High-Volume DID',
    provider: 'twilio',
    assignedAgentId: 'agent-marketing-2',
    assignedAgentName: 'Alex - Outbound Marketing & Leads Qualifier',
    status: 'active',
    capabilities: { voice: true, sms: false },
    createdAt: '2026-09-18T09:30:00Z',
    updatedAt: '2026-09-18T09:30:00Z',
  },
  {
    id: 'num-3',
    phoneNumber: '+971 4 819 2200',
    friendlyName: 'Dubai & UAE Regional Clinic Line',
    provider: 'vapi',
    assignedAgentId: 'agent-healthcare-3',
    assignedAgentName: 'Dr. Sarah - Clinic & Dental Appointment Setter',
    status: 'active',
    capabilities: { voice: true, sms: true },
    createdAt: '2026-09-22T12:00:00Z',
    updatedAt: '2026-09-22T12:00:00Z',
  },
];

export const INITIAL_CALL_LOGS: VoiceCall[] = [
  {
    id: 'call-101',
    agentId: 'agent-receptionist-1',
    agentName: 'Maya - 24/7 Frontdesk AI Receptionist',
    direction: 'inbound',
    fromNumber: '+1 (555) 732-9011',
    toNumber: '+1 (415) 890-3421',
    callerName: 'Michael Chang',
    status: 'completed',
    durationSeconds: 142,
    recordingUrl: 'https://cdn.example.com/audio/call-101.mp3',
    sentiment: 'positive',
    qualificationStatus: 'booked_appointment',
    summary: 'Caller inquired about enterprise CRM setup and pricing. Booked a virtual consultation for Thursday at 2:30 PM. Requested calendar invite via email.',
    transcript: [
      { role: 'agent', text: 'Thank you for calling Apex Business Services! My name is Maya, your AI receptionist. How may I direct your call or assist you today?', timestamp: '00:02' },
      { role: 'caller', text: 'Hi Maya, I wanted to find out more about your multi-tenant CRM automation. We run an agency with 15 team members.', timestamp: '00:09' },
      { role: 'agent', text: 'That sounds like a great fit! Our platform offers automated WhatsApp broadcasting, unified inboxes, and integrated AI voice receptionists. Would you like to schedule a 15-minute walkthrough with our senior tech specialist?', timestamp: '00:22' },
      { role: 'caller', text: 'Yes, that would be ideal. What availability do you have this Thursday?', timestamp: '00:30' },
      { role: 'agent', text: 'We have an opening at 2:30 PM Eastern Time on Thursday. May I confirm your full name and best email address for the calendar invite?', timestamp: '00:39' },
      { role: 'caller', text: 'My name is Michael Chang, email is michael.chang@techscale.io.', timestamp: '00:48' },
      { role: 'agent', text: 'Perfect! I have reserved Thursday at 2:30 PM for you, Michael. You will receive an invitation email shortly. Is there anything else I can help you with today?', timestamp: '01:05' },
      { role: 'caller', text: 'No, that was super fast. Thank you Maya!', timestamp: '01:12' },
      { role: 'agent', text: 'You are very welcome! Have a wonderful day.', timestamp: '01:16' },
    ],
    actionItems: [
      'Calendar invite dispatched to michael.chang@techscale.io for Thu 2:30 PM',
      'Tagged contact as Enterprise Agency Lead (15 seats)',
      'Sent WhatsApp confirmation message with Zoom link',
    ],
    costEstimate: 0.12,
    startedAt: '2026-10-10T14:15:00Z',
    endedAt: '2026-10-10T14:17:22Z',
    createdAt: '2026-10-10T14:15:00Z',
  },
  {
    id: 'call-102',
    agentId: 'agent-marketing-2',
    agentName: 'Alex - Outbound Marketing & Leads Qualifier',
    direction: 'outbound',
    fromNumber: '+1 (650) 438-7712',
    toNumber: '+971 50 505 3639',
    callerName: 'Apex Dental Care (Dr. Tariq)',
    status: 'completed',
    durationSeconds: 198,
    recordingUrl: 'https://cdn.example.com/audio/call-102.mp3',
    sentiment: 'interested',
    qualificationStatus: 'hot_lead',
    summary: 'Outbound campaign call to extracted dental clinic lead. Dr. Tariq was very impressed with the automated WhatsApp + Voice receptionist capabilities for night-time patient emergencies. Requested customized proposal.',
    transcript: [
      { role: 'agent', text: 'Hi Dr. Tariq! This is Alex calling from Jeose CRM. I saw Apex Dental Care has fantastic reviews in Dubai and wanted to share how our AI receptionist handles patient bookings when your clinic is closed.', timestamp: '00:04' },
      { role: 'caller', text: 'Hello Alex. Yes, we currently miss quite a few patient calls after 8 PM because our reception is closed. How does it work?', timestamp: '00:18' },
      { role: 'agent', text: 'Our AI answers immediately in a warm voice, checks your appointment slots, answers pricing questions, and sends the patient a WhatsApp booking confirmation instantly.', timestamp: '00:32' },
      { role: 'caller', text: 'Can it understand both English and Arabic or Urdu accents?', timestamp: '00:41' },
      { role: 'agent', text: 'Absolutely! It supports English, Arabic, and Urdu natively with ultra-low latency and zero robotic delays. We can even plug in your clinic’s custom treatments and pricing list.', timestamp: '00:54' },
      { role: 'caller', text: 'Send me a demo video and the pricing package on my WhatsApp number.', timestamp: '01:08' },
      { role: 'agent', text: 'I am sending the WhatsApp package right now to this number. Our healthcare specialist will follow up tomorrow at 11 AM to assist with setup. Have a great evening!', timestamp: '01:24' },
    ],
    actionItems: [
      'Pushed to Deals Pipeline: Stage "Demo/Proposal Sent" ($1,200/yr)',
      'Triggered automated WhatsApp media brochure with demo video',
      'Scheduled follow-up reminder for tomorrow at 11:00 AM',
    ],
    costEstimate: 0.16,
    startedAt: '2026-10-10T11:20:00Z',
    endedAt: '2026-10-10T11:23:18Z',
    createdAt: '2026-10-10T11:20:00Z',
  },
  {
    id: 'call-103',
    agentId: 'agent-receptionist-1',
    agentName: 'Maya - 24/7 Frontdesk AI Receptionist',
    direction: 'inbound',
    fromNumber: '+1 (555) 489-1120',
    toNumber: '+1 (415) 890-3421',
    callerName: 'Sophia Lorenza',
    status: 'completed',
    durationSeconds: 84,
    recordingUrl: 'https://cdn.example.com/audio/call-103.mp3',
    sentiment: 'neutral',
    qualificationStatus: 'callback_requested',
    summary: 'Caller asked for billing department regarding an invoice dispute. Receptionist collected invoice number #INV-8821 and scheduled an urgent callback from accounting.',
    transcript: [
      { role: 'agent', text: 'Thank you for calling Apex Business Services! My name is Maya, your AI receptionist. How may I direct your call or assist you today?', timestamp: '00:03' },
      { role: 'caller', text: 'Hi, I received invoice #8821 yesterday and have a query about the domain fee charge.', timestamp: '00:12' },
      { role: 'agent', text: 'I understand, Sophia. I have noted down invoice number INV-8821. Our finance officer will review the statement and call you back within two business hours.', timestamp: '00:26' },
      { role: 'caller', text: 'Thank you, please reach me at this same mobile number.', timestamp: '00:32' },
      { role: 'agent', text: 'Noted with thanks! Have a wonderful day ahead.', timestamp: '00:38' },
    ],
    actionItems: [
      'Created Support Ticket: #INV-8821 Billing Inquiry',
      'Assigned callback task to Finance Team',
    ],
    costEstimate: 0.08,
    startedAt: '2026-10-09T16:04:00Z',
    endedAt: '2026-10-09T16:05:24Z',
    createdAt: '2026-10-09T16:04:00Z',
  },
  {
    id: 'call-104',
    agentId: 'agent-marketing-2',
    agentName: 'Alex - Outbound Marketing & Leads Qualifier',
    direction: 'outbound',
    fromNumber: '+1 (650) 438-7712',
    toNumber: '+1 (555) 902-3341',
    callerName: 'Downtown Legal Group',
    status: 'completed',
    durationSeconds: 62,
    sentiment: 'neutral',
    qualificationStatus: 'not_interested',
    summary: 'Marketing lead caller engaged office manager. Currently using an existing legacy PBX system under multi-year contract. Politely marked as not interested for 6 months.',
    transcript: [
      { role: 'agent', text: 'Hello! This is Alex calling from Jeose CRM. How are you doing today?', timestamp: '00:03' },
      { role: 'caller', text: 'Doing fine, what is this regarding?', timestamp: '00:07' },
      { role: 'agent', text: 'I am reaching out regarding automated intake receptionists for legal consults.', timestamp: '00:15' },
      { role: 'caller', text: 'We just signed a two-year contract with our telecom vendor last month so we cannot change right now.', timestamp: '00:24' },
      { role: 'agent', text: 'Understood completely! Thank you for letting me know. I will make a note and we can reconnect down the line. Have a productive week!', timestamp: '00:35' },
    ],
    actionItems: [
      'Marked as Contract Bound (Review in Q2 2027)',
    ],
    costEstimate: 0.05,
    startedAt: '2026-10-09T10:12:00Z',
    endedAt: '2026-10-09T10:13:02Z',
    createdAt: '2026-10-09T10:12:00Z',
  },
];

export const INITIAL_CAMPAIGNS: VoiceCampaign[] = [
  {
    id: 'camp-1',
    name: 'Q4 Dental & Healthcare Clinics Lead Outreach',
    agentId: 'agent-marketing-2',
    agentName: 'Alex - Outbound Marketing & Leads Qualifier',
    status: 'running',
    callingWindowStart: '09:00',
    callingWindowEnd: '18:00',
    maxConcurrentCalls: 3,
    retryAttempts: 2,
    totalLeads: 24,
    completedCalls: 18,
    answeredCalls: 14,
    qualifiedLeads: 8,
    leads: [
      { id: 'lead-c1', name: 'Apex Dental Care', phone: '+971 50 505 3639', status: 'completed', qualification: 'hot_lead', category: 'Dentist', notes: 'Interested in night-time AI receptionist' },
      { id: 'lead-c2', name: 'Prime Smiles Ortho', phone: '+971 55 234 8891', status: 'completed', qualification: 'booked_appointment', category: 'Dentist', notes: 'Demo meeting booked' },
      { id: 'lead-c3', name: 'Elite Derma Clinic', phone: '+971 52 901 4455', status: 'completed', qualification: 'callback_requested', category: 'Healthcare', notes: 'Call back at 4 PM' },
      { id: 'lead-c4', name: 'Bright Smile Studio', phone: '+1 (555) 304-9122', status: 'calling', category: 'Dentist' },
      { id: 'lead-c5', name: 'Skyline Medical Group', phone: '+1 (555) 883-2009', status: 'pending', category: 'Healthcare' },
      { id: 'lead-c6', name: 'Family Health Center', phone: '+1 (555) 441-9876', status: 'pending', category: 'Healthcare' },
    ],
    createdAt: '2026-10-08T09:00:00Z',
    updatedAt: '2026-10-10T15:30:00Z',
  },
  {
    id: 'camp-2',
    name: 'Real Estate Brokers & Property VIP Follow-Up',
    agentId: 'agent-marketing-2',
    agentName: 'Alex - Outbound Marketing & Leads Qualifier',
    status: 'paused',
    callingWindowStart: '10:00',
    callingWindowEnd: '17:00',
    maxConcurrentCalls: 2,
    retryAttempts: 1,
    totalLeads: 15,
    completedCalls: 6,
    answeredCalls: 5,
    qualifiedLeads: 3,
    leads: [
      { id: 'lead-r1', name: 'Harbor Real Estate', phone: '+971 4 332 9911', status: 'completed', qualification: 'hot_lead', category: 'Real Estate' },
      { id: 'lead-r2', name: 'Bayview Luxury Villas', phone: '+971 50 882 1100', status: 'completed', qualification: 'callback_requested', category: 'Real Estate' },
      { id: 'lead-r3', name: 'Emaar Partner Agency', phone: '+971 55 490 2233', status: 'pending', category: 'Real Estate' },
    ],
    createdAt: '2026-10-09T11:00:00Z',
    updatedAt: '2026-10-10T12:00:00Z',
  },
];

export const INITIAL_TELEPHONY_SETTINGS: VoiceTelephonySettings = {
  telephonyProvider: 'twilio',
  twilioAccountSid: '',
  twilioAuthToken: '',
  vapiApiKey: 'vapi_live_••••••••••••••••••••••••',
  retellApiKey: 'key_••••••••••••••••••••••••',
  elevenlabsApiKey: 'xi_••••••••••••••••••••••••',
  inboundWebhookUrl: 'https://api.crmverse.app/api/voice/webhook',
  statusCallbackUrl: 'https://api.crmverse.app/api/voice/status',
  recordingEnabled: true,
  autoPushLeadsToCrm: true,
  autoCreateDeals: true,
  autoSendWhatsappSummary: true,
  dailyCallLimit: 500,
  concurrencyLimit: 5,
};
