import type { Invoice, SalesPerson } from '@/types/invoices';

export const SALES_TEAM: SalesPerson[] = [
  {
    id: 'sp-alina',
    name: 'Alina Khan',
    displayName: 'Alina',
    role: 'Senior Sales & Client Success',
    email: 'alina@wacrm.io',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'sp-maya',
    name: 'Maya Rodriguez',
    displayName: 'Maya',
    role: 'Business Development Lead',
    email: 'maya@wacrm.io',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'sp-hamza',
    name: 'Hamza Tariq',
    displayName: 'Hamza',
    role: 'Technical Solutions Architect',
    email: 'hamza@wacrm.io',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'sp-sarah',
    name: 'Sarah Jenkins',
    displayName: 'Sarah',
    role: 'Key Account Manager',
    email: 'sarah@wacrm.io',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
];

export const SERVICE_PRESETS = [
  {
    description: 'Custom Web Development & Modern Responsive Portal',
    unitPrice: 1200,
  },
  {
    description: 'WhatsApp Cloud Business API Integration & Bot Workflows',
    unitPrice: 650,
  },
  {
    description: 'E-Commerce Store Setup with Multi-Currency Checkout',
    unitPrice: 1500,
  },
  {
    description: 'Annual Ultra-Fast Managed Cloud Hosting & SSL Certificate',
    unitPrice: 299,
  },
  {
    description: 'CRM Workspace Setup, Contact Migration & Team Onboarding',
    unitPrice: 450,
  },
  {
    description: 'Monthly Performance Marketing & Lead Generation Funnel',
    unitPrice: 850,
  },
  {
    description: 'UI/UX Brand Identity System & Figma Interactive Prototype',
    unitPrice: 550,
  },
];

// Completely randomized clients with fresh business names, personal names, mobile numbers & emails
export function createRandomizedInvoices(): Invoice[] {
  return [
    // --- INVOICES ---
    {
      id: 'inv-101',
      referenceNumber: 'TRJ-INV-260930-N89B',
      type: 'invoice',
      title: 'WhatsApp Automation & Cloud Bot Infrastructure',
      clientName: 'Rashid Al-Maktoum',
      companyName: 'Nexus Cloud Technologies LLC',
      clientEmail: 'billing@nexuscloud.io',
      clientPhone: '+971 52 481 9204',
      clientAddress: 'Level 18, Emirates Towers, Sheikh Zayed Road, Dubai, UAE',
      currency: 'AED',
      subtotal: 1850.0,
      taxRate: 5,
      taxAmount: 92.5,
      discountAmount: 50.0,
      totalAmount: 1892.5,
      paidAmount: 1892.5,
      status: 'paid',
      issueDate: '2026-09-30',
      dueDate: '2026-10-14',
      createdAt: '2026-09-30T10:30:00.000Z',
      salesPerson: SALES_TEAM[0], // Alina
      items: [
        {
          id: 'it-101',
          description: 'Enterprise WhatsApp Multi-Agent Shared Inbox & Routing',
          quantity: 1,
          unitPrice: 1200.0,
          total: 1200.0,
          inclusions: 'Includes 5 agent seats, SLA response timer & automated greeting flow',
        },
        {
          id: 'it-102',
          description: 'Dedicated Cloud Webhook Server & SSL Setup',
          quantity: 1,
          unitPrice: 650.0,
          total: 650.0,
          inclusions: 'High-availability server hosted in UAE region',
        },
      ],
      notes: 'Paid in full. Official receipt generated.',
      paymentTerms: 'Payment Completed',
    },
    {
      id: 'inv-102',
      referenceNumber: 'TRJ-INV-260929-U44C',
      type: 'invoice',
      title: 'E-Commerce Store Setup with Multi-Currency Checkout',
      clientName: 'Sophia Sterling',
      companyName: 'Urban Bloom Interior Design Studio',
      clientEmail: 'sophia@urbanbloomdesign.com',
      clientPhone: '+971 56 319 8842',
      clientAddress: 'Building 6, Dubai Design District (d3), Dubai, UAE',
      currency: 'AED',
      subtotal: 1500.0,
      taxRate: 5,
      taxAmount: 75.0,
      discountAmount: 0,
      totalAmount: 1575.0,
      paidAmount: 750.0,
      status: 'partial',
      issueDate: '2026-09-29',
      dueDate: '2026-10-13',
      createdAt: '2026-09-29T14:15:00.000Z',
      salesPerson: SALES_TEAM[1], // Maya
      items: [
        {
          id: 'it-103',
          description: 'Custom Web Development & Modern Responsive Portal',
          quantity: 1,
          unitPrice: 1200.0,
          total: 1200.0,
          inclusions: 'Figma to Next.js responsive conversion with dark mode',
        },
        {
          id: 'it-104',
          description: 'WhatsApp Cart Abandonment & Order Status Trigger',
          quantity: 1,
          unitPrice: 300.0,
          total: 300.0,
          inclusions: 'Automated 1-click WhatsApp checkout reminders',
        },
      ],
      notes: '50% advance received. Balance due upon deployment to production.',
      paymentTerms: '50% Advance, 50% on Delivery',
    },
    {
      id: 'inv-103',
      referenceNumber: 'TRJ-INV-260928-S71A',
      type: 'invoice',
      title: 'Equipment Catalog & Lead Webhook Flow',
      clientName: 'Tariq Mansoor',
      companyName: 'Al-Safwa Heavy Machinery & Industrial Tr',
      clientEmail: 'tariq@alsafwatrading.sa',
      clientPhone: '+966 55 812 7390',
      clientAddress: 'Warehouse 14, Industrial Area 2, Riyadh, Saudi Arabia',
      currency: 'SAR',
      subtotal: 2100.0,
      taxRate: 5,
      taxAmount: 105.0,
      discountAmount: 0,
      totalAmount: 2205.0,
      paidAmount: 0,
      status: 'sent',
      issueDate: '2026-09-28',
      dueDate: '2026-10-12',
      createdAt: '2026-09-28T09:20:00.000Z',
      salesPerson: SALES_TEAM[2], // Hamza
      items: [
        {
          id: 'it-105',
          description: 'Digital Product Catalog with WhatsApp Direct Click-to-Chat',
          quantity: 1,
          unitPrice: 1450.0,
          total: 1450.0,
          inclusions: 'Interactive PDF & WhatsApp catalog sync with item SKUs',
        },
        {
          id: 'it-106',
          description: 'CRM Workspace Setup & Staff Onboarding (5 Users)',
          quantity: 1,
          unitPrice: 650.0,
          total: 650.0,
          inclusions: 'Live training session with workflow documentation',
        },
      ],
      notes: 'Invoice sent to client. Awaiting bank transfer confirmation.',
      paymentTerms: 'Net 14 Days',
    },
    {
      id: 'inv-104',
      referenceNumber: 'TRJ-INV-260925-V12F',
      type: 'invoice',
      title: 'Client Onboarding Portal & Secure Form Flow',
      clientName: 'Elena Rostova',
      companyName: 'Vanguard Legal & Corporate Advisors',
      clientEmail: 'elena.rostova@vanguardlegal.ae',
      clientPhone: '+971 58 642 1195',
      clientAddress: 'DIFC Gate Precinct 4, Level 5, Dubai, UAE',
      currency: 'AED',
      subtotal: 950.0,
      taxRate: 5,
      taxAmount: 47.5,
      discountAmount: 0,
      totalAmount: 997.5,
      paidAmount: 0,
      status: 'overdue',
      issueDate: '2026-09-10',
      dueDate: '2026-09-24',
      createdAt: '2026-09-10T11:00:00.000Z',
      salesPerson: SALES_TEAM[3], // Sarah
      items: [
        {
          id: 'it-107',
          description: 'Interactive Client KYC & Registration Pipeline',
          quantity: 1,
          unitPrice: 950.0,
          total: 950.0,
          inclusions: 'Encrypted document upload & WhatsApp instant status alert',
        },
      ],
      notes: 'Payment reminder sent. Follow-up scheduled for tomorrow.',
      paymentTerms: 'Payment past due - Net 14',
    },
    {
      id: 'inv-105',
      referenceNumber: 'TRJ-INV-260923-H88M',
      type: 'invoice',
      title: 'Annual High-Speed Managed Cloud Hosting',
      clientName: 'Omar Farooq',
      companyName: 'Horizon Hospitality & Dining Group',
      clientEmail: 'finance@horizonhospitality.ae',
      clientPhone: '+971 50 924 6713',
      clientAddress: 'Jumeirah Beach Road, Villa 22, Dubai, UAE',
      currency: 'AED',
      subtotal: 598.0,
      taxRate: 5,
      taxAmount: 29.9,
      discountAmount: 0,
      totalAmount: 627.9,
      paidAmount: 0,
      status: 'draft',
      issueDate: '2026-09-23',
      dueDate: '2026-10-07',
      createdAt: '2026-09-23T16:40:00.000Z',
      salesPerson: SALES_TEAM[0], // Alina
      items: [
        {
          id: 'it-108',
          description: 'Annual Ultra-Fast Managed Cloud Hosting & Daily Backups (2 Sites)',
          quantity: 2,
          unitPrice: 299.0,
          total: 598.0,
          inclusions: '99.9% uptime SLA with automated off-site backups',
        },
      ],
      notes: 'Draft proposal pending client review of renewal terms.',
      paymentTerms: 'Due upon receipt',
    },

    // --- QUOTATIONS ---
    {
      id: 'qt-101',
      referenceNumber: 'TRJ-QT-260930-S99L',
      type: 'quotation',
      title: 'Omnichannel Marketing Suite & Green Tick Verification',
      clientName: 'Zayd Al-Nuaimi',
      companyName: 'Starlight Creative Media & Production',
      clientEmail: 'zayd@starlightmedia.ae',
      clientPhone: '+971 55 930 4421',
      clientAddress: 'Media City, Building 9, Dubai, UAE',
      currency: 'AED',
      subtotal: 2850.0,
      taxRate: 5,
      taxAmount: 142.5,
      discountAmount: 0,
      totalAmount: 2992.5,
      paidAmount: 0,
      status: 'sent',
      issueDate: '2026-09-30',
      dueDate: '2026-10-21',
      createdAt: '2026-09-30T15:00:00.000Z',
      validUntil: '2026-10-21',
      salesPerson: SALES_TEAM[1], // Maya
      items: [
        {
          id: 'it-109',
          description: 'WhatsApp Official Green Tick Verified Business Application',
          quantity: 1,
          unitPrice: 1200.0,
          total: 1200.0,
          inclusions: 'Meta compliance preparation and submission handling',
        },
        {
          id: 'it-110',
          description: 'Monthly Performance Marketing & Lead Generation Funnel',
          quantity: 1,
          unitPrice: 850.0,
          total: 850.0,
          inclusions: 'Targeted campaign setup with analytics dashboard',
        },
        {
          id: 'it-111',
          description: 'UI/UX Brand Identity System & Interactive Figma Assets',
          quantity: 1,
          unitPrice: 800.0,
          total: 800.0,
          inclusions: 'Full typography, color tokens, and web component kit',
        },
      ],
      notes: 'Estimate valid for 21 days from issue date.',
      paymentTerms: '40% Deposit, 40% on Beta, 20% Final Signoff',
    },
    {
      id: 'qt-102',
      referenceNumber: 'TRJ-QT-260927-E45W',
      type: 'quotation',
      title: 'Member Retention WhatsApp Automation & Renewals',
      clientName: 'Jessica Miller',
      companyName: 'Elevate Fitness & Wellness Centers',
      clientEmail: 'jessica@elevatefitness.ae',
      clientPhone: '+971 52 617 3850',
      clientAddress: 'Marina Plaza, Level 12, Dubai Marina, UAE',
      currency: 'AED',
      subtotal: 1350.0,
      taxRate: 5,
      taxAmount: 67.5,
      discountAmount: 0,
      totalAmount: 1417.5,
      paidAmount: 0,
      status: 'accepted',
      issueDate: '2026-09-27',
      dueDate: '2026-10-18',
      createdAt: '2026-09-27T12:30:00.000Z',
      validUntil: '2026-10-18',
      salesPerson: SALES_TEAM[0], // Alina
      items: [
        {
          id: 'it-112',
          description: 'Membership Renewal Notification Bot with Secure Payment Links',
          quantity: 1,
          unitPrice: 850.0,
          total: 850.0,
          inclusions: 'Auto-triggers 7 days and 1 day before expiration',
        },
        {
          id: 'it-113',
          description: 'WhatsApp QR Code Check-in Workflow',
          quantity: 1,
          unitPrice: 500.0,
          total: 500.0,
          inclusions: 'Instant check-in confirmation message sent to member',
        },
      ],
      notes: 'Quotation accepted by client. Ready for conversion to official invoice.',
      paymentTerms: 'Net 7 Days',
    },
    {
      id: 'qt-103',
      referenceNumber: 'TRJ-QT-260925-G10R',
      type: 'quotation',
      title: 'Property Lead Capture Funnel & Auto-Dispatch',
      clientName: 'Fahad Al-Harbi',
      companyName: 'Golden Falcon Real Estate Brokers',
      clientEmail: 'fahad@goldenfalconrealty.sa',
      clientPhone: '+966 54 209 8813',
      clientAddress: 'King Fahd Road, Al-Sahafa District, Riyadh, Saudi Arabia',
      currency: 'SAR',
      subtotal: 3200.0,
      taxRate: 5,
      taxAmount: 160.0,
      discountAmount: 0,
      totalAmount: 3360.0,
      paidAmount: 0,
      status: 'draft',
      issueDate: '2026-09-25',
      dueDate: '2026-10-15',
      createdAt: '2026-09-25T14:10:00.000Z',
      validUntil: '2026-10-15',
      salesPerson: SALES_TEAM[2], // Hamza
      items: [
        {
          id: 'it-114',
          description: 'Real Estate WhatsApp Interactive Catalog with Property Search Bot',
          quantity: 1,
          unitPrice: 2200.0,
          total: 2200.0,
          inclusions: 'Filters by budget, area, bedrooms with instant PDF brochure download',
        },
        {
          id: 'it-115',
          description: 'Agent Round-Robin Assignment & CRM Integration',
          quantity: 1,
          unitPrice: 1000.0,
          total: 1000.0,
          inclusions: 'Instant WhatsApp notification to assigned property consultant',
        },
      ],
      notes: 'Initial quotation presented to managing director.',
      paymentTerms: '50% on Signing, 50% on Go-Live',
    },

    // --- RECEIPTS ---
    {
      id: 'rec-101',
      referenceNumber: 'TRJ-REC-260930-N89B',
      type: 'receipt',
      title: 'Payment Receipt: WhatsApp Automation Setup',
      clientName: 'Rashid Al-Maktoum',
      companyName: 'Nexus Cloud Technologies LLC',
      clientEmail: 'billing@nexuscloud.io',
      clientPhone: '+971 52 481 9204',
      clientAddress: 'Level 18, Emirates Towers, Sheikh Zayed Road, Dubai, UAE',
      currency: 'AED',
      subtotal: 1850.0,
      taxRate: 5,
      taxAmount: 92.5,
      discountAmount: 50.0,
      totalAmount: 1892.5,
      paidAmount: 1892.5,
      status: 'paid',
      issueDate: '2026-09-30',
      dueDate: '2026-09-30',
      createdAt: '2026-09-30T10:45:00.000Z',
      salesPerson: SALES_TEAM[0], // Alina
      linkedInvoiceRef: 'TRJ-INV-260930-N89B',
      paymentMethod: 'bank_transfer',
      transactionId: 'TXN-DXB-992140',
      items: [
        {
          id: 'it-116',
          description: 'Payment in Full for Invoice TRJ-INV-260930-N89B',
          quantity: 1,
          unitPrice: 1892.5,
          total: 1892.5,
        },
      ],
      notes: 'Settled via Corporate Bank Transfer. All services activated.',
      paymentTerms: 'Payment Completed',
    },
    {
      id: 'rec-102',
      referenceNumber: 'TRJ-REC-260929-U44C',
      type: 'receipt',
      title: 'Payment Receipt: 50% Advance Store Setup',
      clientName: 'Sophia Sterling',
      companyName: 'Urban Bloom Interior Design Studio',
      clientEmail: 'sophia@urbanbloomdesign.com',
      clientPhone: '+971 56 319 8842',
      clientAddress: 'Building 6, Dubai Design District (d3), Dubai, UAE',
      currency: 'AED',
      subtotal: 750.0,
      taxRate: 0,
      taxAmount: 0,
      discountAmount: 0,
      totalAmount: 750.0,
      paidAmount: 750.0,
      status: 'paid',
      issueDate: '2026-09-29',
      dueDate: '2026-09-29',
      createdAt: '2026-09-29T14:40:00.000Z',
      salesPerson: SALES_TEAM[1], // Maya
      linkedInvoiceRef: 'TRJ-INV-260929-U44C',
      paymentMethod: 'credit_card',
      transactionId: 'ch_3Pq9812UAE441',
      items: [
        {
          id: 'it-117',
          description: '50% Milestone 1 Deposit for Invoice TRJ-INV-260929-U44C',
          quantity: 1,
          unitPrice: 750.0,
          total: 750.0,
        },
      ],
      notes: 'Credit Card payment processed successfully via Stripe.',
      paymentTerms: 'Partial Settlement',
    },
    {
      id: 'rec-103',
      referenceNumber: 'TRJ-REC-260926-C81L',
      type: 'receipt',
      title: 'Payment Receipt: Shipment Webhook Integration',
      clientName: 'Vikram Mehta',
      companyName: 'Crestview Global Logistics FZC',
      clientEmail: 'accounts@crestviewlogistics.com',
      clientPhone: '+971 54 783 2901',
      clientAddress: 'JAFZA South Zone, Warehouse 8, Dubai, UAE',
      currency: 'AED',
      subtotal: 650.0,
      taxRate: 5,
      taxAmount: 32.5,
      discountAmount: 0,
      totalAmount: 682.5,
      paidAmount: 682.5,
      status: 'paid',
      issueDate: '2026-09-26',
      dueDate: '2026-09-26',
      createdAt: '2026-09-26T16:15:00.000Z',
      salesPerson: SALES_TEAM[2], // Hamza
      paymentMethod: 'credit_card',
      transactionId: 'TXN-JAF-110482',
      items: [
        {
          id: 'it-118',
          description: 'Payment for Live Shipment Tracking Webhook',
          quantity: 1,
          unitPrice: 682.5,
          total: 682.5,
        },
      ],
      notes: 'Settled in full.',
      paymentTerms: 'Payment Completed',
    },
  ];
}

export const INITIAL_INVOICES: Invoice[] = createRandomizedInvoices();
